version: '3.3'

networks:
  mainnet:
    driver: bridge

services:
  mydb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'taskdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mainnet



  taskserver:
    build:
      dockerfile: dockerfile
    restart: "no"
    environment:
      databaseAddress: "mydb:3306"
    networks:
      - mainnet
    depends_on:
      - mydb

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 8181:8181
    networks:
      - mainnet
    environment:
      - DOMAIN=taskserver
      - AUTH_TOKEN=2I0FB9g4lhPsbjMgHtyKfke44vD_XG3uBLFBTSdduCwFMdL2
      - PORT=8080

# Names our volume
volumes:
  my-db: